# Generated by Django 5.2.17 on 2026-08-09 14:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('protection_end_date', models.DateField()),
                ('sido', models.CharField(max_length=50)),
                ('sigungu', models.CharField(max_length=50)),
                ('detail_address', models.CharField(blank=True, max_length=255, null=True)),
                ('housing_type', models.CharField(choices=[('MONTHLY_RENT', '월세'), ('JEONSE', '전세'), ('OWNED', '자가'), ('FREE', '무상거주')], max_length=20)),
                ('income_type', models.CharField(choices=[('EARNED', '근로소득'), ('BUSINESS', '사업소득'), ('OTHER_ASSET', '기타재산소득'), ('NONE', '소득없음')], max_length=20)),
                ('employment_type', models.CharField(choices=[('UNEMPLOYED', '미취업'), ('EMPLOYED', '취업'), ('PART_TIME', '아르바이트'), ('SELF_EMPLOYED', '자영업')], max_length=20)),
                ('education_status', models.CharField(choices=[('ENROLLED', '재학'), ('LEAVE_OF_ABSENCE', '휴학'), ('GRADUATED', '졸업'), ('HIGH_SCHOOL_OR_BELOW', '고등학교 이하')], max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
