# Generated by Django 5.2.17 on 2026-08-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='detail_address',
            new_name='detailAddress',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='education_status',
            new_name='educationStatus',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employment_type',
            new_name='employmentType',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='housing_type',
            new_name='housingType',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='income_type',
            new_name='incomeType',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='protection_end_date',
            new_name='protectionEndDate',
        ),
    ]
