# Generated by Django 5.2.17 on 2026-08-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_refreshtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='detailAddress',
            new_name='detail_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='educationStatus',
            new_name='education_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employmentType',
            new_name='employment_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='housingType',
            new_name='housing_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='incomeType',
            new_name='income_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='protectionEndDate',
            new_name='protection_end_date',
        ),
    ]
