# Generated by Django 5.2.17 on 2026-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_education_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='housing_situation',
            field=models.CharField(blank=True, choices=[('STABLE', '안정적으로 거주하고 있어요'), ('MOVING', '이사할 집을 찾고 있어요'), ('SEEKING_INDEPENDENCE', '독립할 집을 찾고 있어요'), ('BURDEN', '주거비가 부담스러워요'), ('PREPARING_END', '곧 보호종료라 주거를 준비해야 해요'), ('UNKNOWN', '아직 잘 모르겠어요')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('MONTHLY_RENT', '월세'), ('JEONSE', '전세'), ('OWNED', '자가'), ('FREE', '무상 거주'), ('FACILITY', '시설·그룹홈 등')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='income_type',
            field=models.CharField(blank=True, choices=[('EARNED', '근로소득'), ('BUSINESS', '사업소득'), ('OTHER_ASSET', '기타·재산소득'), ('NONE', '현재 소득이 없어요')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='living_status',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='needed_help',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='protection_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='protection_type',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL_CARE', '아동양육시설'), ('GROUP_HOME', '공동생활가정'), ('FOSTER_CARE', '가정위탁'), ('ETC', '기타'), ('UNKNOWN', '잘 모르겠어요')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sigungu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='support_received',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
