# Generated by Django 5.2.17 on 2026-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_birth_date_alter_user_housing_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='protection_status',
            field=models.CharField(blank=True, choices=[('PROTECTED', '아직 보호 중이에요'), ('SCHEDULED', '보호 종료 예정이에요'), ('ENDED', '보호 종료했어요')], max_length=20, null=True),
        ),
    ]
