# Generated by Django 5.2.17 on 2026-08-12 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', '진행 중'), ('STRUCTURED', '상황 구조화 완료'), ('CONNECTED', '조력자 연계 완료'), ('CLOSED', '종료')], default='ACTIVE', max_length=20)),
                ('latest_risk_level', models.CharField(choices=[('NONE', '판독 전'), ('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('CRITICAL', '긴급')], default='NONE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_check_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskCheckMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', '사용자'), ('ASSISTANT', 'AI 챗봇')], max_length=20)),
                ('type', models.CharField(choices=[('TEXT', '텍스트'), ('IMAGE', '이미지')], default='TEXT', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='chat/risk-check/%Y/%m/%d/')),
                ('risk_level', models.CharField(choices=[('NONE', '판독 전'), ('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('CRITICAL', '긴급')], default='NONE', max_length=20)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.riskchecksession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StructuredRiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=30)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('counterpart', models.CharField(blank=True, max_length=255)),
                ('situation_summary', models.TextField(blank=True)),
                ('risk_type', models.CharField(blank=True, max_length=255)),
                ('risk_grade', models.CharField(choices=[('NONE', '판독 전'), ('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('CRITICAL', '긴급')], default='NONE', max_length=20)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_report', to='chat.riskchecksession')),
            ],
        ),
        migrations.CreateModel(
            name='SupportConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_to', models.CharField(choices=[('SUPPORT_STAFF', '조력자'), ('COUNSELOR', '상담사'), ('EMERGENCY', '긴급 지원')], max_length=30)),
                ('consent', models.BooleanField(default=False)),
                ('forced_connection', models.BooleanField(default=False)),
                ('notice', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_connection', to='chat.riskchecksession')),
            ],
        ),
        migrations.CreateModel(
            name='RiskCheckMessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.riskcheckmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_check_message_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='unique_risk_message_report_per_user')],
            },
        ),
    ]
