# Generated by Django 5.2.17 on 2026-08-20 12:13

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_ordering_and_connection_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcheckmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.risk_check_upload_path),
        ),
        migrations.AlterField(
            model_name='riskcheckmessage',
            name='type',
            field=models.CharField(choices=[('TEXT', '텍스트'), ('IMAGE', '이미지'), ('DOCUMENT', '문서(PDF/DOCX)')], default='TEXT', max_length=10),
        ),
    ]
