# Generated by Django 5.2.17 on 2026-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='issue_guide_text',
            field=models.CharField(blank=True, help_text='발급 안내 문구', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='issue_guide_url',
            field=models.URLField(blank=True, help_text='발급받기 버튼 연결 URL', null=True),
        ),
    ]
