# Generated by Django 5.2.17 on 2026-08-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_checklistitem_issue_guide_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='알림 클릭 시 이동할 대상 객체 ID', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DEADLINE', '신청 마감'), ('COMMENT', '댓글'), ('REPLY', '답글'), ('ETC', '기타')], default='ETC', max_length=20),
        ),
    ]
