# Generated by Django 5.2.17 on 2026-08-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_notification_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DEADLINE', '신청 마감'), ('COMMENT', '댓글'), ('REPLY', '답글'), ('PROTECTION_END', '보호종료'), ('ETC', '기타')], default='ETC', max_length=20),
        ),
    ]
