# Generated by Django 5.2.17 on 2026-08-20 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_delete_orphaned_soft_deleted_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnonymousAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_anonymous_aliases', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_aliases', to='community.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'author'), name='unique_post_anonymous_author'), models.UniqueConstraint(fields=('post', 'sequence'), name='unique_post_anonymous_sequence')],
            },
        ),
    ]
