# Generated by Django 5.2.17 on 2026-08-20 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_backfill_post_anonymous_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('reporter', 'post'), name='unique_post_report_per_reporter'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('reporter', 'comment'), name='unique_comment_report_per_reporter'),
        ),
    ]
