# Generated by Django 5.2.17 on 2026-08-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('SPAM', '스팸, 광고'), ('SEXUAL', '음란성, 선정성 글'), ('HATE', '혐오, 반응 조장 발언'), ('PRIVACY', '개인정보 노출'), ('MISINFORMATION', '의도적인 거짓 정보 확산')], max_length=200),
        ),
    ]
