# Generated by Django 5.2.17 on 2026-08-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('HOUSING', '주거'), ('EMPLOYMENT', '취업'), ('FINANCE', '금융/자립수당'), ('EDUCATION', '교육'), ('MENTAL_HEALTH', '심리/정서'), ('ETC', '기타')], max_length=20)),
                ('target_condition', models.TextField(help_text='지원 대상 조건 설명')),
                ('organization', models.CharField(help_text='주관 기관', max_length=100)),
                ('application_start', models.DateField(blank=True, null=True)),
                ('application_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
