# Generated by Django 5.2.17 on 2026-08-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='application_method',
            field=models.TextField(default=' ', help_text='언제까지 신청하나요? (신청 방법/기간)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='eligibility',
            field=models.TextField(default=' ', help_text='내가 신청할 수 있나요? (신청 자격)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='required_documents',
            field=models.TextField(default=' ', help_text='무엇을 준비해야 하나요? (준비 서류)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(help_text='이 지원사업은? (소개)'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='target_condition',
            field=models.TextField(help_text='AI 큐레이션 매칭용 키워드 텍스트'),
        ),
    ]
