# Generated by Django 5.2.17 on 2026-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_policy_application_method_policy_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='consult_link',
            field=models.URLField(blank=True, help_text='상담 신청 링크', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='consult_phone',
            field=models.CharField(blank=True, help_text='상담 전화번호', max_length=20, null=True),
        ),
    ]
