# Generated by Django 5.2.17 on 2026-08-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_policy_application_method_policy_eligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='region_sido',
            field=models.CharField(blank=True, help_text='특정 시도 대상 정책이면 입력, 전국 대상이면 비워둠', max_length=50, null=True),
        ),
    ]
