# Generated by Django 5.2.17 on 2026-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_policy_region_sido'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationMatchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_signature', models.CharField(db_index=True, max_length=16)),
                ('policy_ids_hash', models.CharField(max_length=16)),
                ('matched_result', models.JSONField(help_text='AI가 생성한 매칭 결과 (policy_id, match_reason 쌍의 리스트)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('profile_signature', 'policy_ids_hash')},
            },
        ),
    ]
