# Generated by Django 5.2.17 on 2026-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_curationmatchcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='consult_link',
            field=models.URLField(blank=True, help_text='상담 신청/안내 링크', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='consult_phone',
            field=models.CharField(blank=True, help_text='상담 전화번호', max_length=20, null=True),
        ),
    ]
