# Generated by Django 5.2.17 on 2026-08-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_policyscrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='eligibility_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='policy',
            name='required_document_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
