# Generated by Django 5.2.17 on 2026-08-19 07:24

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_migrate_policy_detail_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='age_ranges',
            field=models.JSONField(blank=True, default=list, help_text='대상 연령 구간 (복수 선택 가능)', validators=[home.models.validate_age_ranges]),
        ),
        migrations.AddField(
            model_name='policy',
            name='income_criteria',
            field=models.JSONField(blank=True, default=list, help_text='대상 소득 기준 (복수 선택 가능)', validators=[home.models.validate_income_criteria]),
        ),
        migrations.AddField(
            model_name='policy',
            name='protection_types',
            field=models.JSONField(blank=True, default=list, help_text='대상 보호유형 (복수 선택 가능)', validators=[home.models.validate_protection_types]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='eligibility_items',
            field=models.JSONField(blank=True, default=list, validators=[home.models.validate_eligibility_items]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='required_document_items',
            field=models.JSONField(blank=True, default=list, validators=[home.models.validate_required_document_items]),
        ),
    ]
