# Generated by Django 5.2.17 on 2026-08-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_policy_age_ranges_policy_income_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='support_amount',
            field=models.CharField(blank=True, help_text='지원 금액 (예: 월 30만원, 최대 500만원 등 자유 텍스트)', max_length=200, null=True),
        ),
    ]
