# Generated by Django 5.2.17 on 2026-08-19 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_policy_eligibility_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityJudgeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_label', models.CharField(max_length=200)),
                ('profile_signature', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_caches', to='home.policy')),
            ],
            options={
                'unique_together': {('policy', 'eligibility_label', 'profile_signature')},
            },
        ),
    ]
