# Generated by Django 5.2.17 on 2026-08-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_eligibilityjudgecache'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curationmatchcache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curationmatchcache',
            name='cache_type',
            field=models.CharField(default='CURATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='curationmatchcache',
            name='matched_result',
            field=models.JSONField(help_text='AI가 생성한 매칭 결과 (policy_id, match_reason 등)'),
        ),
        migrations.AlterUniqueTogether(
            name='curationmatchcache',
            unique_together={('cache_type', 'profile_signature', 'policy_ids_hash')},
        ),
    ]
