# Generated by Django 5.2.17 on 2026-08-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_curationmatchcache_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationmatchcache',
            name='cache_type',
            field=models.CharField(choices=[('CURATION', '홈 큐레이션'), ('POLICY_MATCH', '정책 목록/상세 매칭')], default='CURATION', max_length=20),
        ),
    ]
