# Generated by Django 5.2.17 on 2026-08-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_load_policy_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='eligibility_items',
            field=models.JSONField(blank=True, default=list, help_text='자격요건 항목 리스트. 예: [{"label": "만 18세 이상 자립준비청년"}]'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='required_document_items',
            field=models.JSONField(blank=True, default=list, help_text='서류 항목 리스트. 예: [{"label": "주민등록등본", "issueMethod": "정부24", "linkUrl": "https://..."}]'),
        ),
    ]
