# Generated by Django 5.2.17 on 2026-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_fill_policy_support_and_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_id',
            field=models.CharField(blank=True, help_text='원본 정책DB의 정책 ID (예: POL-CEN-001). 외부 데이터 매칭용 키.', max_length=50, null=True, unique=True),
        ),
    ]
