# Generated by Django 5.2.17 on 2026-08-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_fill_policy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationmatchcache',
            name='cache_type',
            field=models.CharField(choices=[('CURATION', '홈 큐레이션')], default='CURATION', max_length=20),
        ),
        migrations.CreateModel(
            name='PolicyMatchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_signature', models.CharField(db_index=True, max_length=16)),
                ('match_level', models.CharField(choices=[('HIGH', '높음'), ('MEDIUM', '보통'), ('LOW', '낮음')], max_length=10)),
                ('match_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='캐시 유효기간 판정 기준')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_caches', to='home.policy')),
            ],
            options={
                'unique_together': {('policy', 'profile_signature')},
            },
        ),
    ]
