# Generated by Django 5.2.17 on 2026-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_split_schedule_policy_summary_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='required_document_items',
            field=models.JSONField(blank=True, default=list, help_text='서류 항목 리스트. 예: [{"label": "주민등록등본", "description": "주소, 세대 구성 정보를 확인하는 서류", "issueMethod": "정부24", "linkUrl": "https://..."}]'),
        ),
    ]
