# Generated by Django 5.2.17 on 2026-08-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_policy_required_document_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='required_document_items',
            field=models.JSONField(blank=True, default=list, help_text='서류 항목 리스트. 예: [{"label": "주민등록등본", "description": "주소, 세대 구성 정보를 확인하는 서류", "issueMethod": "정부24에서 무료 발급", "preparation": "본인 인증", "issuer": "정부24", "linkUrl": "https://..."}]'),
        ),
    ]
