# Generated by Django 5.2.17 on 2026-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_sync_existing_policy_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='사용자 화면 노출 여부. 끄면 목록/상세/추천/챗봇에서 조회되지 않는다. 데이터는 남으므로 다시 켜면 그대로 복구된다.'),
        ),
    ]
