# Generated by Django 5.2.17 on 2026-08-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('license_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_level', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('CRITICAL', '긴급')], max_length=10)),
                ('status', models.CharField(choices=[('RECEIVED', '접수'), ('ASSIGNED', '배정'), ('IN_PROGRESS', '상담 진행 중'), ('RESOLVED', '해결'), ('CLOSED', '종료')], default='RECEIVED', max_length=20)),
                ('risk_type', models.CharField(choices=[('HOUSING_FRAUD', '주거 사기'), ('FINANCIAL_SCAM', '금융 사기'), ('LEGAL', '법률'), ('EMPLOYMENT', '취업'), ('WELFARE', '복지'), ('SAFETY', '신변 안전'), ('OTHER', '기타')], default='OTHER', max_length=30)),
                ('summary', models.TextField()),
                ('structured_report', models.JSONField(blank=True, default=dict)),
                ('pre_interview', models.JSONField(blank=True, default=list)),
                ('consent_scope', models.JSONField(blank=True, default=list)),
                ('linkage_consented', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consult_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consult_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consult_requests', to='b2g.organization')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status', '-received_at'], name='b2g_consult_organiz_01584b_idx'), models.Index(fields=['organization', 'urgency_level', '-received_at'], name='b2g_consult_organiz_3a5e93_idx'), models.Index(fields=['organization', 'risk_type'], name='b2g_consult_organiz_aacafb_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='b2g.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_membership')],
            },
        ),
    ]
