# Generated by Django 5.2.17 on 2026-08-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FINANCE', '금융 & 경제'), ('HOUSING', '주거 & 일상자립'), ('EMPLOYMENT', '취업 & 진로')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('card_summary', models.CharField(help_text='카드에 보이는 고정 짧은 설명', max_length=200)),
                ('source_facts', models.JSONField(default=list, help_text='AI 요약의 재료가 되는 검증된 팩트 리스트')),
                ('content', models.TextField(help_text='상세 본문(번호 섹션+표 포함, Markdown). AI가 손대지 않음')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='briefings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BriefingSummaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_signature', models.CharField(db_index=True, max_length=16)),
                ('generated_summary', models.JSONField(help_text='AI가 생성한 요약 (불릿 리스트)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_caches', to='briefing.briefing')),
            ],
            options={
                'unique_together': {('briefing', 'profile_signature')},
            },
        ),
    ]
