# Generated by Django 5.2.17 on 2026-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='color',
            field=models.CharField(choices=[('blue', '파랑'), ('green', '초록'), ('red', '빨강')], default='blue', help_text='카드 색상 박스', max_length=10),
        ),
        migrations.AddField(
            model_name='briefing',
            name='icon',
            field=models.CharField(choices=[('chart', '차트'), ('clock', '시계'), ('computer', '컴퓨터'), ('court', '법원'), ('delivery', '배송'), ('document', '문서'), ('graduation', '학사모'), ('graph', '그래프'), ('heart', '하트'), ('home', '집'), ('idcard', '신분증'), ('letter', '편지'), ('magnifier', '돋보기'), ('money', '돈'), ('phone', '전화'), ('pigbank', '돼지저금통')], default='document', help_text='카드 아이콘 (FE 아이콘 에셋 이름)', max_length=20),
        ),
    ]
