# Generated by Django 5.2.17 on 2026-08-19 16:32

import briefing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0004_load_briefing_cardnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefing',
            name='content_tables',
            field=models.JSONField(blank=True, default=list, help_text='표로 노출되는 콘텐츠. content 의 어느 섹션에 붙는지를 section 으로 지정한다. 예: [{"section": "2. 통장 쪼개기", "headers": ["구분", "설명"], "rows": [["수입통장", "메인 허브"]]}]', validators=[briefing.models.validate_content_tables]),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='content',
            field=models.TextField(help_text='상세 본문(번호 섹션, Markdown). AI가 손대지 않음'),
        ),
    ]
